#!/usr/bin/env fish
if not test -d "/Volumes/Glitch/"
  echo "Can't access source directory: /Volumes/Glitch/"
  exit
end
if not test -d "/Volumes/Files/Music/Glitch/"
  echo "Can't access target directory: /Volumes/Files/Music/Glitch/"
  exit
end

rsync -ahvrESH8 --delete --progress --stats --exclude=".*/" --exclude=".*" "/Volumes/Glitch/" "/Volumes/Files/Music/Glitch/"
rm -f "/Volumes/Files/Music/Glitch/.backup"
date -u > "/Volumes/Files/Music/Glitch/.backup"

mkdir -p ~/.cache/dada
echo (date +"%a, %b %d %Y %X %z") > ~/.cache/dada/backup-glitch