#!/usr/bin/env fish
if not test -d "/Volumes/Glitch/"
  echo "Can't access source directory: /Volumes/Glitch/"
  exit
end
if not test -d "/Volumes/Files/Backups/msikma/Glitch/"
  echo "Can't access target directory: /Volumes/Files/Backups/msikma/Glitch/"
  exit
end

rsync -ahvrESH8 --delete --progress --stats --exclude=".*/" --exclude=".*" "/Volumes/Glitch/" "/Volumes/Files/Backups/msikma/Glitch/"
rm -f "/Volumes/Files/Backups/msikma/Glitch/.backup"
date -u > "/Volumes/Files/Backups/msikma/Glitch/.backup"
