#!/usr/bin/env fish

echo "backup-dbs         - Backs up databases from MAMP to /Work/"
echo "backup-music       - Backs up music"
echo "backup-files       - Backs up various other things (VMs, pictures, etc.)"
echo "backup-source      - Backs up source code directories (source, client projects, projects)"
echo "backup-zoo-music   - Backs up subset of music to the Happy Zoo"
